//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AnimationCurveManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AnimationCurveManager), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetAnimationCurve", GetAnimationCurve);
		L.RegFunction("Traverse", Traverse);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("curveInfoList", get_curveInfoList, set_curveInfoList);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAnimationCurve(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AnimationCurveManager obj = (AnimationCurveManager)ToLua.CheckObject<AnimationCurveManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.AnimationCurve o = obj.GetAnimationCurve(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Traverse(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AnimationCurveManager obj = (AnimationCurveManager)ToLua.CheckObject<AnimationCurveManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.Traverse(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_curveInfoList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AnimationCurveManager obj = (AnimationCurveManager)o;
			System.Collections.Generic.List<AnimationCurveManager.CurveInfo> ret = obj.curveInfoList;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curveInfoList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_curveInfoList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			AnimationCurveManager obj = (AnimationCurveManager)o;
			System.Collections.Generic.List<AnimationCurveManager.CurveInfo> arg0 = (System.Collections.Generic.List<AnimationCurveManager.CurveInfo>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<AnimationCurveManager.CurveInfo>));
			obj.curveInfoList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index curveInfoList on a nil value");
		}
	}
}

